### PR TITLE
[GSSoC - 23] feat: Separating the functionality of Notification button to add & delete roles. 

### LINKED ISSUE #34: [GSSoC - 23] feat: Separating the functionality of Notification button to add delete roles.
## Issue
Hello, @roshan1337d first of all this bot is really amazing 😀,
While exploring the features of [coding-contests-companion](https://github.com/roshan1337d/coding-contests-companion) bot, I found out that **Role Addition** & **Role Removal** functionality of the notification button in `./setup-contest.js` can be separated and enhanced.

## Current Behavior
Right now there is only one button present **Notifications** which does both role addition and removal tasks. So for a new Discord user, it's a little confusing as the _follow up_ message is shown to the user after he presses the button.<br/>

## Possible Solution
I have a solution for this task that will reduce the confusion of the user by adding one more button **Stop Notifications**.

**Possible Implementation**

<hr/>

> :bulb: **Tip:** Please assign this issue to me, I will be glad to contribute to this amazing repository

### PR DESCRIPTION
**Pull request by JatinSharma32**
## Related Issue
Closes #34 

## How Has This Been Tested?

- [x] Unit Testing
- [x] Code Formatting(Prettier) 😢

## Screenshots (if appropriate):
Provided in #34

## Description:
Sorry, it just went out of my head to disable the Prettier which exploring the Codebase. I intended to only format `./interactions/notifications.js` & `./commands/setup-contest.js` but ended up formatting 5-6 files for no reason.
It's a silly mistake I will take care of it next time.

### CODE REVIEW

**Review by roshan1337d — CHANGES_REQUESTED** [review]
Thanks for the PR. Great work 😃

But please just modify the required files. You can copy paste the content of the files you modified unnecessarily from the repo after disabling your code formatter.

**Comment by JatinSharma32** [comment]
Yup surely 🙂

**Comment by JatinSharma32** [comment]
### Fixed those formatting issues in my latest commit ([ca9ba8b](https://github.com/roshan1337d/coding-contests-companion/pull/42/commits/ca9ba8bb4ca081e4f997a53818cc6e8322784161))
- have a look at [files](https://github.com/roshan1337d/coding-contests-companion/pull/42/files)

**Comment by JatinSharma32** [comment]
Are you considering this Pull Request or i have to make a new one, because I have already made the requested changes so please have a look.

**Review by roshan1337d — APPROVED** [review]
All good, great work 🙌

**Pull request merged**
