### PR TITLE
Converted all plain text messages to embeds

### PR DESCRIPTION
**Pull request by devsargam**

### CODE REVIEW

**Comment by devsargam** [comment]
Done as indicated in #5

**Comment by devsargam** [comment]
@roshan1337d first one has no purpose of doing so as it gives same result.

**Comment by roshan1337d** [comment]
I see... There's already `ephemeral: true` in deferReply. You're right, ignore the 1st one.

**Review by roshan1337d — APPROVED** [review]
All good, nice work 👍

**Pull request merged**
